Repository ember-graphql/ember-apollo-client, pull requests merged in 2019-10, with the labels that each got.

#315 Rework tests and dummy app
  addon/services/apollo.js
  ember-cli-build.js
  tests/acceptance/array-watch-query-test.js
  tests/acceptance/computed-with-watch-query-test.js
  tests/acceptance/query-and-unsubscribe-test.js
  tests/acceptance/watch-query-test.js
  tests/dummy/app/components/character-item.js
  tests/dummy/app/components/movie-card.js
  tests/dummy/app/components/movie-detail.js
  tests/dummy/app/controllers/index.js
  tests/dummy/app/gql/mutations/change-character-name.graphql
  tests/dummy/app/gql/mutations/change-movie-title.graphql
  tests/dummy/app/gql/queries/characters.graphql
  tests/dummy/app/gql/queries/human.graphql
  tests/dummy/app/gql/queries/movie.graphql
  tests/dummy/app/gql/queries/movies.graphql
  tests/dummy/app/gql/queries/reviews.graphql
  tests/dummy/app/index.html
  tests/dummy/app/instance-initializers/mock-graphql.js
  tests/dummy/app/models/.gitkeep
  tests/dummy/app/router.js
  tests/dummy/app/routes/anakin.js
  tests/dummy/app/routes/index.js
  tests/dummy/app/routes/luke.js
  tests/dummy/app/routes/movie.js
  tests/dummy/app/routes/reviews.js
  tests/dummy/app/schema.graphql
  tests/dummy/app/styles/app.css
  tests/dummy/app/templates/anakin.hbs
  tests/dummy/app/templates/characters.hbs
  tests/dummy/app/templates/components/character-item.hbs
  tests/dummy/app/templates/components/movie-card.hbs
  tests/dummy/app/templates/components/movie-detail.hbs
  tests/dummy/app/templates/index.hbs
  tests/dummy/app/templates/luke.hbs
  tests/dummy/app/templates/movie.hbs
  tests/dummy/app/templates/reviews.hbs
  tests/fixtures/test-schema.graphql
  tests/helpers/start-pretender.js
Labels: Type: Internal

#316 Remove Episode GraphQL type from dummy app
  tests/dummy/app/gql/mutations/create-review.graphql
  tests/dummy/app/routes/new-review.js
  tests/dummy/app/schema.graphql
  tests/unit/routes/new-review-test.js
Labels: Type: Internal

#318 Add deprecation for for default value of keepGraphqlFileExtension
  README.md
  ember-cli-build.js
  index.js
Labels: Type: Enhancement

#321 Fix IE 11 Symbol.iterator
  addon/-private/apollo/query-manager.js
Labels: Type: Bug

#323 Fix references in the README to apollo docs
  README.md
Labels: Type: Documentation
