Repository ember-graphql/ember-apollo-client, pull requests merged in 2019-09, with the labels that each got.

#298 Using nested fragments creates invalid graphql document
  tests/unit/build/graphql-filter-test.js
  tests/unit/build/test-fragment-with-fragment.graphql
  tests/unit/build/test-query-with-nested-fragment.graphql
  yarn.lock
Labels: Type: Internal

#305 Remove unused dev dep & Upgrade to Ember v3.13 & Cleanup dependencies
  package.json
  yarn.lock
Labels: Type: Dependencies

#306 Remove unused prod dependencies
  CHANGELOG.md
  README.md
  package.json
  yarn.lock
Labels: Type: Breaking Change

#307 Add Release Drafter as GitHub Actions
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Type: Tooling

#308 Add tests with delayed responses
  tests/acceptance/watch-query-test.js
  tests/dummy/app/routes/anakin.js
  tests/dummy/app/templates/anakin.hbs
  tests/unit/services/apollo-test.js
Labels: Type: Internal

#309 Cleanup to use async/await and move away from Ember get/set when possible
  addon/-private/mixins/base-query-manager.js
  addon/-private/mixins/component-query-manager.js
  addon/-private/mixins/object-query-manager.js
  addon/-private/mixins/route-query-manager.js
  addon/services/apollo.js
  tests/acceptance/query-and-unsubscribe-test.js
  tests/dummy/app/routes/anakin.js
  tests/dummy/app/routes/characters.js
  tests/dummy/app/routes/luke.js
  tests/dummy/app/routes/new-review.js
  tests/unit/mixins/component-query-manager-test.js
  tests/unit/mixins/object-query-manager-test.js
  tests/unit/mixins/route-query-manager-test.js
  tests/unit/services/apollo-test.js
Labels: Type: Internal

#310 Don't create EmberObject for returned data & Add public alternative to unsubscribe from watchQuery
  CHANGELOG.md
  README.md
  addon/index.js
  addon/services/apollo.js
  tests/acceptance/array-watch-query-test.js
  tests/dummy/app/gql/queries/reviews.graphql
  tests/dummy/app/router.js
  tests/dummy/app/routes/reviews.js
  tests/dummy/app/templates/reviews.hbs
  tests/unit/get-observable-test.js
  tests/unit/unsubscribe-test.js
Labels: Type: Breaking Change

#312 Return the actual returned data, not a copy
  addon/services/apollo.js
  addon/utils/copy-with-extras.js
  tests/acceptance/computed-with-watch-query-test.js
  tests/dummy/app/components/character-item.js
  tests/dummy/app/routes/characters.js
  tests/dummy/app/templates/characters.hbs
  tests/dummy/app/templates/components/character-item.hbs
  tests/unit/utils/copy-with-extras-test.js
Labels: Type: Breaking Change

#313 Remove usage of Evented mixin
  CHANGELOG.md
  README.md
  addon/services/apollo.js
  tests/unit/services/apollo-test.js
Labels: Type: Breaking Change
