Repository ember-graphql/ember-apollo-client, pull requests merged in 2020-08, with the labels that each got.

#355 Upgrade to Apollo Client v3
  README.md
  addon/services/apollo.js
  package.json
  tests/dummy/app/services/apollo.js
  tests/unit/mixins/object-query-manager-test.js
  tests/unit/services/apollo-test.js
  yarn.lock
Labels: Type: Feature

#360 Fix tests on apollo client v3
  addon/services/apollo.js
  tests/acceptance/query-and-unsubscribe-test.js
  tests/dummy/app/services/apollo.js
  tests/dummy/app/templates/movie.hbs
Labels: Type: Internal

#361 Remove deprecated mixins
  addon/-private/apollo/query-manager.js
  addon/-private/mixins/base-query-manager.js
  addon/-private/mixins/component-query-manager.js
  addon/-private/mixins/object-query-manager.js
  addon/-private/mixins/route-query-manager.js
  addon/index.js
  tests/dummy/app/mixins/component-query-manager.js
  tests/dummy/app/mixins/object-query-manager.js
  tests/dummy/app/mixins/route-query-manager.js
  tests/unit/mixins/component-query-manager-test.js
  tests/unit/mixins/object-query-manager-test.js
  tests/unit/mixins/route-query-manager-test.js
Labels: Type: Breaking Change

#362 Remove deprecated overwriting of options using computed properties
  addon/-private/deprecate-computed.js
  addon/services/apollo.js
  tests/unit/services/apollo-test.js
Labels: Type: Breaking Change

#359 V3
  .eslintrc.js
  README.md
  addon/-private/apollo/query-manager.js
  addon/-private/deprecate-computed.js
  addon/-private/mixins/base-query-manager.js
  addon/-private/mixins/component-query-manager.js
  addon/-private/mixins/object-query-manager.js
  addon/-private/mixins/route-query-manager.js
  addon/index.js
  addon/services/apollo.js
  config/ember-try.js
  index.js
  package.json
  tests/acceptance/query-and-unsubscribe-test.js
  tests/dummy/app/app.js
  tests/dummy/app/mixins/component-query-manager.js
  tests/dummy/app/mixins/object-query-manager.js
  tests/dummy/app/mixins/route-query-manager.js
  tests/dummy/app/router.js
  tests/dummy/app/services/apollo.js
  tests/dummy/app/templates/movie.hbs
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  tests/test-helper.js
  tests/unit/mixins/component-query-manager-test.js
  tests/unit/mixins/object-query-manager-test.js
  tests/unit/mixins/route-query-manager-test.js
  tests/unit/services/apollo-test.js
  yarn.lock
Labels: Type: Breaking Change

#365 Allow graphql v15 and tell webpack about react
  index.js
  package.json
Labels: Type: Bug
