Repository ember-graphql/ember-apollo-client, pull requests merged in 2020-04, with the labels that each got.

#342 Upgrade to Ember v3.17 & Drop node v8
  .editorconfig
  .eslintrc.js
  .github/workflows/ci.yml
  .template-lintrc.js
  CONTRIBUTING.md
  README.md
  config/ember-try.js
  package.json
  testem.js
  tests/acceptance/array-watch-query-test.js
  tests/dummy/app/app.js
  tests/dummy/app/resolver.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/.gitkeep
  tests/dummy/app/templates/components/create-review.hbs
  tests/dummy/app/templates/components/movie-card.hbs
  tests/dummy/app/templates/index.hbs
  tests/dummy/app/templates/movie.hbs
  tests/dummy/app/templates/new-review.hbs
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/optional-features.json
  yarn.lock
Labels: Type: Breaking Change

#344 Update README to show new fragment import syntax
  README.md
Labels: Type: Documentation

#343 Use WeakMap for storing observables and unsubscribeFn
  addon/index.js
  addon/services/apollo.js
  tests/dummy/app/services/apollo.js
  tests/unit/get-observable-test.js
  tests/unit/services/apollo-test.js
  tests/unit/unsubscribe-test.js
Labels: Type: Bug

#345 Upgrade to Prettier v2.0.0
  addon/-private/apollo/query-manager.js
  addon/-private/apollo/setup-hooks.js
  addon/-private/mixins/base-query-manager.js
  addon/services/apollo.js
  addon/utils/inject.js
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  package.json
  tests/acceptance/array-watch-query-test.js
  tests/acceptance/computed-with-watch-query-test.js
  tests/acceptance/mutations-test.js
  tests/acceptance/query-and-unsubscribe-test.js
  tests/acceptance/watch-query-test.js
  tests/dummy/app/components/create-review.js
  tests/dummy/app/components/movie-card.js
  tests/dummy/app/components/movie-detail.js
  tests/dummy/app/instance-initializers/mock-graphql.js
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/helpers/setup.js
  tests/helpers/start-pretender.js
  tests/unit/-private/query-manager-hooks-component-test.js
  tests/unit/-private/query-manager-hooks-object-test.js
  tests/unit/-private/query-manager-hooks-route-test.js
  tests/unit/-private/query-manager-macro-decorator-test.js
  tests/unit/build/graphql-filter-test.js
  tests/unit/mixins/component-query-manager-test.js
  tests/unit/mixins/object-query-manager-test.js
  tests/unit/mixins/route-query-manager-test.js
  tests/unit/services/apollo-test.js
  yarn.lock
Labels: Type: Internal

#346 Fix repo URL in package.json
  package.json
Labels: Type: Internal

#347 Add myself to package.json maintainers list
  package.json
Labels: Type: Internal

#348 docs: using with typescript
  README.md
Labels: Type: Documentation
